### ISSUE TITLE
Accessories page - layout

### ISSUE THREAD

**Issue by ram718** [devn5900/humane-governor-8062#9]
- [x] Creating the page layout
- [x] Importing necessary images
- [x] Styling accordingly

**Comment by devn5900** [comment]
bro, Please make the api request for limited data in accessories/products page. where you are fetching the data.

ex.  https://busy-jade-mussel-sock.cyclic.app/products?type=accessories&_page=1&_limit=15

 *implement pagination for page 1,2,3.....  with the same limit ( 15 )


Thanks bro
